name: myey
description: Our solution is for healthy eyesight by identifying its weaknesses earlier.  The problem I see is that in my surroundings people are very hesitant to visit the doctor to get their eyes tested but they delay the process so much which will slowly weaken their eyes more and more.  We are working on a solution to test the eyes of individuals to give an estimate of their visual power and testing their eyes on the app rewards them. So they can redeem those points in clinics and hospitals for discounts.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  camera: ^0.9.4+14
  google_ml_kit: ^0.7.3
  image_picker: ^0.8.4+10
  speech_to_text: ^5.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
